# Configuration pour build_runner
# Utilisé pour la génération de code (Freezed, Riverpod, etc.)

targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          union_value_case: pascal
      
      riverpod_generator:
        enabled: true
      
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
