// Mocks generated by Mockito 5.4.6 from annotations
// in tokse_flutter/test/features/signalement/domain/usecases/get_signalements_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tokse_flutter/core/errors/failures.dart' as _i5;
import 'package:tokse_flutter/features/signalement/domain/entities/signalement_entity.dart'
    as _i6;
import 'package:tokse_flutter/features/signalement/domain/repositories/i_signalement_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ISignalementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignalementRepository extends _i1.Mock
    implements _i3.ISignalementRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          List<_i6.SignalementEntity>>> getSignalements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSignalements,
          [],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
          this,
          Invocation.method(
            #getSignalements,
            [],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
          this,
          Invocation.method(
            #getSignalements,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>> getSignalementById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSignalementById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.SignalementEntity>(
          this,
          Invocation.method(
            #getSignalementById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.SignalementEntity>(
          this,
          Invocation.method(
            #getSignalementById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.SignalementEntity>>> getUserSignalements(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSignalements,
          [userId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
          this,
          Invocation.method(
            #getUserSignalements,
            [userId],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
          this,
          Invocation.method(
            #getUserSignalements,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>
      getSignalementsByCategory(String? category) => (super.noSuchMethod(
            Invocation.method(
              #getSignalementsByCategory,
              [category],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
              this,
              Invocation.method(
                #getSignalementsByCategory,
                [category],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
              this,
              Invocation.method(
                #getSignalementsByCategory,
                [category],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>
      getSignalementsByStatus(String? status) => (super.noSuchMethod(
            Invocation.method(
              #getSignalementsByStatus,
              [status],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
              this,
              Invocation.method(
                #getSignalementsByStatus,
                [status],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.SignalementEntity>>(
              this,
              Invocation.method(
                #getSignalementsByStatus,
                [status],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.SignalementEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>> createSignalement({
    required String? titre,
    required String? description,
    required String? categorie,
    required double? latitude,
    required double? longitude,
    String? adresse,
    List<String>? photosUrls,
    String? audioUrl,
    bool? isUrgent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignalement,
          [],
          {
            #titre: titre,
            #description: description,
            #categorie: categorie,
            #latitude: latitude,
            #longitude: longitude,
            #adresse: adresse,
            #photosUrls: photosUrls,
            #audioUrl: audioUrl,
            #isUrgent: isUrgent,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.SignalementEntity>(
          this,
          Invocation.method(
            #createSignalement,
            [],
            {
              #titre: titre,
              #description: description,
              #categorie: categorie,
              #latitude: latitude,
              #longitude: longitude,
              #adresse: adresse,
              #photosUrls: photosUrls,
              #audioUrl: audioUrl,
              #isUrgent: isUrgent,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.SignalementEntity>(
          this,
          Invocation.method(
            #createSignalement,
            [],
            {
              #titre: titre,
              #description: description,
              #categorie: categorie,
              #latitude: latitude,
              #longitude: longitude,
              #adresse: adresse,
              #photosUrls: photosUrls,
              #audioUrl: audioUrl,
              #isUrgent: isUrgent,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SignalementEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateSignalementStatus(
    String? signalementId,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSignalementStatus,
          [
            signalementId,
            newStatus,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateSignalementStatus,
            [
              signalementId,
              newStatus,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateSignalementStatus,
            [
              signalementId,
              newStatus,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addFelicitation(
          String? signalementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFelicitation,
          [signalementId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addFelicitation,
            [signalementId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addFelicitation,
            [signalementId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeFelicitation(
          String? signalementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFelicitation,
          [signalementId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeFelicitation,
            [signalementId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeFelicitation,
            [signalementId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSignalement(
          String? signalementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSignalement,
          [signalementId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteSignalement,
            [signalementId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteSignalement,
            [signalementId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Set<String>>> getUserFelicitations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFelicitations,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, Set<String>>>.value(
            _FakeEither_0<_i5.Failure, Set<String>>(
          this,
          Invocation.method(
            #getUserFelicitations,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, Set<String>>>.value(
                _FakeEither_0<_i5.Failure, Set<String>>(
          this,
          Invocation.method(
            #getUserFelicitations,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Set<String>>>);
}
